# Generated by Django 6.0.3 on 2026-03-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="prica",
            new_name="price",
        ),
    ]
